### ISSUE TITLE
USER STORY: Poll for best time to running 

### ISSUE THREAD

**Issue by GiovaniFonseca** [Giov3ss/My-First-Agile-Project#3]
As a **user** I can **vote in the poll for the best time to run** so that **I can be prepared for the next running challenge**

## Acceptance Criteria

- The option should be provided as a checkbox
- The checkbox should be “checked” by default
- The option should appear next to the submit button
- After submitting a list with best times should appear

## Tasks
- [ ] Design the user interface 
- [ ] Creat HTML and CSS
- [ ] Create a list, so after the user submit appear with the best time to run
